config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'pages#dashboard'
  get 'search', to: 'pages#search'
  get 'cart', to: 'pages#cart_page'
  get 'store', to: 'pages#store'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :line_items, only: [:destroy] do
    member do
      post :add_item
      patch :adjust_item
    end
  end

  resources :grocery_lists, only: [:new, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/grocery_list.rb
class GroceryList < ApplicationRecord
  belongs_to :user
  has_many :line_items
  has_many :items, through: :line_items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_stores
  has_many :grocery_lists, through: :line_item
  has_many :stores, through: :item_stores
  has_one_attached :photo
  include PgSearch::Model

  pg_search_scope :search_by_name_and_category,
                  against: %i[name category],
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :name, :price, presence: true
end

app/models/item_store.rb
class ItemStore < ApplicationRecord
  belongs_to :item
  belongs_to :store

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :grocery_list
  validates :quantity, presence: true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :item_store
  has_many :item, through: :item_store

  validates :name, :address, presence: true
end

app/models/store_list.rb
class StoreList < ApplicationRecord
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :grocery_list

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  # skip_before_action :authenticate_user!, only: [:store]
end

app/controllers/grocery_lists_controller.rb
class GroceryListsController < ApplicationController
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # before_action :authenticate_user!
  # skip_before_action :verify_authenticity_token

  def add_item
    @grocery_list = User.find_by(email: "anna@gmail.com").grocery_list # user's grocery list
    @line_item = LineItem.new(item_id: params[:id], quantity: 1, grocery_list: @grocery_list) # key value pair, hard-coded quantity
    @line_item.save
    redirect_to search_path # stay on the same page
  end

  def adjust_item
    @line_item = LineItem.find(params[:id])
    if @line_item.update(line_item_params)
      # Broadcast Turbo Stream to update DOM
      html = render_to_string(template: 'pages/search', locals: { line_item: @line_item })
      turbo_stream.append(:quantity_updates, html: html)
      head :ok
    else
      render status: :unprocessable_entity
    end
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to search_path
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def search
    # @items = sorting(Item.all)
    # Search
    if params[:query].present?
      records = Item.search_by_name_and_category(params[:query])
      @items = sorting(records)

    else
      records_shuffle = Item.where("id % 17 = 0").offset(4).limit(50).shuffle
      @items = sorting(records_shuffle)

    end
    # Grocerylist
    @line_items = GroceryList.find_by(user: User.find_by(email: "anna@gmail.com")).line_items
  end

  def sorting(records)
    if params[:sort_order] == "asc"
      return records.sort_by { |item| item[:price] }
    elsif params[:sort_order] == "desc"
      return records.sort_by { |item| -item[:price] }
    else
      return records
    end
  end

  def dashboard
    @grocery_list = GroceryList.find_by(user: User.find_by(email: "anna@gmail.com"))
    @line_items = @grocery_list.line_items
    @item_id_hash = {}
    @counter = 0

    @grocery_list.items.each do |item|
      # Find the ID of the current item
      id = Item.find_by_id(item).id
      # Find all items with the same name as the current item
      items = Item.where(name: item.name)
      # Find the item with the highest price among items with the same name
      highest_price = items.max_by(&:price)
      # Calculate the price difference between the highest priced item and the current item
      price_difference = (highest_price.price - item.price)
      # Store the item's ID, name, and price difference in @item_id_hash
      @item_id_hash[id] = { name: item.name, price: price_difference }
    end

    @grocery_list.line_items.each do |item|
      # Check if the item_id exists in @item_id_hash
      if @item_id_hash[item.item_id]
        # If it exists, calculate the total price difference for this item
        item_difference = @item_id_hash[item.item_id][:price] * item.quantity
        # Add the price difference to the counter
        @counter += item_difference
        # raise
      end
    end

    # Iterate over each line item again to update the quantity in @item_id_hash
    @line_items.each do |line_item|
      item_id = line_item.item_id
      quantity = line_item.quantity

      # If the item_id exists in the hash, update the quantity by adding the new quantity
      if @item_id_hash[item_id]
        # Ensure quantity is initialized to 0 if it's nil
        @item_id_hash[item_id][:quantity] ||= 0
        # Add the new quantity to the existing quantity
        @item_id_hash[item_id][:quantity] += quantity
      else
        item = Item.find(item_id)
        @item_id_hash[item_id] = { name: item.name, quantity: quantity }
      end
    end
    # raise

    @store_hash = cart
    @grocery_store = @store_hash.keys.first
  end

  def cart_page
    @store_hash = cart
    render :cart
  end

  def store
    @stores = Store.all
  end

  private

  def cart
    @grocery_list = GroceryList.find_by(user: User.find_by(email: "anna@gmail.com"))
    @line_items = @grocery_list.line_items
    @store_hash = {}
    @total_price = 0

    @line_items.each do |line|
      key = line.item.stores.first.name
      if @store_hash[key]
        @store_hash[key][:totalprice] += (line.item.price * line.quantity) / 100.0
        @store_hash[key][:items] << line
      else
        @store_hash[key] = {
          totalprice: (line.item.price * line.quantity) / 100.0,
          items: [line]
        }
      end
    end

    @store_hash.each do |_store, value|
      @total_price += value[:totalprice]
    end

    @store_hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SHOPSavvy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/_cart.html.erb
<% rendered_items = Set.new %>
<% store_hash.each_with_index do |(store, value), index| %>
  <% if index < 4 %>
  <div class="user_store">
    <div> <%= store %> </div>
      <% value[:items].each do |lineitem| %>
        <% unless rendered_items.include?(lineitem.item.id) %>
          <div class="store_item"> <%= lineitem.quantity %> x <%= lineitem.item.name %>
           <%# <%= number_to_currency( (lineitem.item.price / 100.0), unit: '$', format: '%u%n') %> </div>
           <div class="store_item_price">
           <%# <%= number_to_currency(((lineitem.item.price * lineitem.quantity) / 100.0), unit: '$', format: '%u%n') %>
           </div>

          <% rendered_items.add(lineitem.item.id) %>
        <% end %>
      <% end %>
    </div>
  <% else %>
  <% break %>
  <% end %>
<% end %>

app/views/pages/cart.html.erb
<body>
  <%# all products cover entire page, white txt, black backdrop %>
  <div class="product_bar">
    <h4>Your shopping carts</h4>
  </div>

  <div class="cart_body">
    <div class="stores-container">
      <% @store_hash.each do |store, value| %>
      <div class="store">

        <div class="store-details">
          <h2><%= store %></h2>
          <div class="price">
            <h5>Cart: <%= number_to_currency(value[:totalprice], unit: '$', format: '%u%n') %></h5>
          </div>
          <div class="header">
            <div class="column-header">Item</div>
            <%# <div class="column-header">Quantity</div> %>
            <div class="column-header">Price</div>
          </div>
          <% value[:items].each do |lineitem| %>
          <div class="item">
            <div class="line"><%= lineitem.quantity %> x <%= lineitem.item.name %> </div>
            <div class="line-price">$<%= (lineitem.item.price * lineitem.quantity) / 100.0 %></div>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="cart-btns">
      <div class="total">
        <h5>Cart Total</h5>
        <h5><%= number_to_currency(@total_price, unit: '$', format: '%u%n') %></h5>
      </div>

    <div class="btn-row-2">
      <div class="savings-btn">
         <button class="dash_btn"> <%= link_to "View new savings", dashboard_path %> </button>
        <h5><%= number_to_currency(@counter, unit: '$', format: '%u%n') %></h5>
      </div>

      <div class="print-btn">
        <button class="dash_btn"> <%= link_to "Print list", dashboard_path %> </button>
      </div>
      </div>
    </div>

</body>

app/views/pages/dashboard.html.erb
<body>
  <%# <div class="dashboard_background"> %>
  <div class="main">
    <h1>Hello, Nicky </h1>
    <p>Welcome back to your Savvy Shopper dashboard</p>

    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button"
          role="tab" aria-controls="nav-home" aria-selected="true">Savings</button>
        <button class="nav-link" id="nav-list-tab" data-bs-toggle="tab" data-bs-target="#nav-list" type="button"
          role="tab" aria-controls="nav-list" aria-selected="false">Shopping List</button>
        <button class="nav-link" id="nav-stores-tab" data-bs-toggle="tab" data-bs-target="#nav-stores" type="button"
          role="tab" aria-controls="nav-stores" aria-selected="false">Stores</button>
      </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
        <div class="bubbles">
          <div class="savings_bubbles">

            <button class="dash" data-controller="toggle" data-action="click->toggle#toggle_weekly">
              <div class="savings_bubbles" id="weekly">
                <h4>Latest savings</h4>
                <p><%= number_to_currency(@counter / 100.0, unit: '$', format: '%u%n') %></p>
                <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                <path
                  d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
              </svg> %>
              </div>
            </button>

            <button class="dash" data-controller="toggle" data-action="click->toggle#toggle_monthly">
              <div class="savings_bubbles" id="monthly">
                <h4>Monthly Savings </h4>
                <p><%= number_to_currency((@counter * 2.5) / 100.0, unit: '$', format: '%u%n') %></p>
                <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                  <path
                    d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
                </svg> %>
              </div>
            </button>

            <button class="dash" data-controller="toggle" data-action="click->toggle#toggle_yearly">
              <div class="savings_bubbles" id="yearly">
                <h4>Yearly Savings </h4>
                <p><%=number_to_currency((@counter * 8) / 100.0, unit: '$', format: '%u%n') %></p>
                <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                  <path
                    d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
                </svg> %>
              </div>
          </div>
          </button>
        </div>

        <div class="list">
          <div class="savings_list_weekly">
            <h3 class="list_title">Latest savings by item</h3>
            <div class="savings_list_weekly_items">
              <% @item_id_hash.each do |item| %>
              <div class="item_name"> <%= item[1][:name] %> </div>
              <div class="weekly_saving">
                <%= number_to_currency( (item[1][:price] * item[1][:quantity]) / 100.0, unit: '$', format: '%u%n') %>
              </div>
              <% end %>
            </div>
          </div>

          <div data-toggle-target="toggleable" class="savings_list_monthly hidden">
            <h3 class="list_title">Monthly savings by item</h3>
            <div class="savings_list_monthly_items">
              <% @item_id_hash.each do |item| %>
              <div class="item_name"> <%= item[1][:name] %> </div>
              <%= number_to_currency( ((item[1][:price] * item[1][:quantity]) * 2.5) / 100.0 , unit: '$', format: '%u%n') %>
              <% end %>
            </div>
          </div>

          <div data-toggle-target="toggleable" class="savings_list_yearly hidden">
            <h3 class="list_title">Annual savings by item</h3>
            <div class="savings_list_yearly_items">
              <% @item_id_hash.each do |item| %>
              <div class="item_name"> <%= item[1][:name] %> </div>
              <%= number_to_currency( ((item[1][:price] * item[1][:quantity]) * 8) / 100.0 , unit: '$', format: '%u%n') %>
              <% end %>
            </div>
          </div>
        </div>
      </div>


      <div class="tab-pane fade" id="nav-list" role="tabpanel" aria-labelledby="nav-list-tab" tabindex="0">
        <div class="tab-2">
          <div class="product_lists" id="favourite_list">
            <h4>Your shopping list</h4>
            <p>Items you saved recently</p>
            <div class="dash_list">
              <%= render partial: 'cart', locals: { store_hash: @store_hash } %>
            </div>
            <button class="dash_btn" id="dash_grocer"> <%= link_to "Go to Cart", cart_path %> </button>
            <button class="dash_btn" id="dash_grocer"> <%= link_to "Edit list", search_path %> </button>
            <button class="dash_btn" id="dash_grocer"> <%= link_to "Print list", search_path %> </button>
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="nav-stores" role="tabpanel" aria-labelledby="nav-stores-tab" tabindex="0">
        <div class="tab-3">
          <div class="store_list" id="grocer_list">
            <h4>Your stores</h4>
            <p>Stores you shopped at last</p>
            <div class="dash_stores">
              <% @store_hash.each do |grocery_store, _info| %>
              <div class="dash_store"> <%= grocery_store %> </div>
              <% end %>
            </div>
            <button class="dash_btn"> <%= link_to "See all stores", store_path %> </button>
          </div>
        </div>
      </div>

    </div>
  </div>

</body>

app/views/pages/favourite.html.erb
<body>
  <div class="card_columns">

    <h3>this be cards</h3>

  </div>
<div class="card_columns">

    <h3>this besds</h3>

  </div>
<div class="card_columns">

    <h3>this sfs</h3>

  </div>
<div class="card_columns">

    <h3>this be cardads</h3>

  </div>





</body>

app/views/pages/home.html.erb
<div class="banner">
  <div class="home_canvas">
    <div class="container">
      <h1>Everyday savings, simplified</h1>
      <p class="intro">Tired of hopping between stores to find the best grocery deals?
        <br>
        Say goodbye to the hassle and hello to convenience!
        <br>
        We're your one-stop destination for comparing prices from your favourite stores, saving you time, money,
        and unnecessary stress.
      </p>
      <button type="button" class="return_btn" id="dash_btn_spacing">
        <%= link_to "Sign Up", new_user_registration_path %>
      </button>
    </div>
  </div>
</div>

<h3 class="footer_title">Partners</h3>
<div class="footer">
  <div class="stores">
    <div class="store1"><a href="#"></a></div>
    <div class="store2"></div>
    <div class="store3"></div>
    <div class="store4"></div>
    <div class="store5"></div>
    <div class="store6"></div>
  </div>
</div>

app/views/pages/search.html.erb
<body>
  <%# all products cover entire page, white txt, black backdrop %>
  <div class="product_bar">
    <h4>All Products</h4>
  </div>

  <%# search bar similar to all products but colours reversed %>
  <div class="display">

  <%# <div class="col-sm-7 my-3"> %>
  <div class="left_div">
    <div class="product_search">
      <%= form_with url: search_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a product"%>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>

  <div class="select-wrapper">
  <%# <select class="select-field" id="listsorting">
  <option value="descending">Price: High-Low</option>
  <option value="ascending">Price: Low-High</option>
  </select> %>
    <%= form_tag(search_path, method: "get") do %>
    <%= hidden_field_tag :query, params[:query] if params[:query].present? %>
    <%= select_tag :sort_order, options_for_select([["Price: Low to High", "asc"], ["Price: High to Low", "desc"]], params[:sort_order]), prompt: "Sort by Price" %>
    <%= submit_tag "Sort" %>
    <% end %>
  </div>


      <%# left div works fine %>
      <div class="card_wrap">
        <% @items.each do |item|  %>
        <div class="items" id="grocery_items">
          <%= image_tag item.photo_url, height: 120, width: 120, crop: :fill %>
          <div class="item_name"> <%= item.name %> </div>
          <div class="line_details">
            <%= item.stores.first.name %>
            <%= number_to_currency(item.price / 100.0, unit: '$', format: '%u%n') %>
          </div>
          <div class="button">
            <%= button_to 'Add to list', add_item_line_item_path(item), class: "btn btn-outline-primary", method: :post, style: "border-radius: 20px;", 'data-item-id': item.id %>
          </div>
        </div>
        <% end %>
      </div>
    </div>


     <%# grocery items %>
    <div class="right_div">
      <h3 class="header-grocery">Grocery List</h3>
      <div class="list_bar">
        <% @line_items.each do |line| %>
        <div class="line-item">
          <%= image_tag line.item.photo_url, height: 86, width: 110, crop: :fill %>
          <div class="grocery_details">
            <%= line.item.name %>
            <div class="row_2">
              <div>
                <%= line.item.stores.first.name %>:
              </div>
              <div id="price_for_item_<%=line.id%>">
                <%= number_to_currency(((line.item.price * line.quantity) / 100.0), unit: '$', format: '%u%n') %>
                <%# <% line.quantity %>
              </div>
            </div>
            <div class="qty" data-controller="quantity-update" data-quantity-update-line-id-value="<%=line.id%>"
              data-quantity-update-unit-price-value="<%=line.item.price%>">
              <%= form_with model: line, method: :patch, url: adjust_item_line_item_path(line), local: false, data: { turbo_frame: 'quantity_updates' } do |f| %>
              Qty:
              <%= f.number_field :quantity, min: 1, max: 100, data: { line_id: line.id, action: "change->quantity-update#calculate" } %>
              <% f.submit "Update Quantity", data: { disable_with: "Updating..." }%>
              <% end %>
 </div>
          </div>
          <div class="button">
            <%= button_to line_item_path(line), method: :delete, class: "btn btn-outline-danger", style: "border-radius: 20px;" do %>
            <i class="fa fa-trash"></i>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>



      <%= link_to "Generate Shopping List", cart_path, method: :post, class: "return_btn", style: "border-radius: 20px;" %>
    </div>
  </div>
  </div>
</body>

app/views/pages/store.html.erb
<body>
  <div class="product_bar">
  <h4>Store List</h4>
  </div>

  <div class="store-cards">
  <% @stores.each do |store| %>
  <div class="store-card">
    <%= image_tag "#{store.name}.png", style: "width: 200px; height: 200px; border-radius: 100px"%>
    <div class="store-info">
      <div class="store-name">
        <%= store.name %>
      </div>
      <div class="store-address">
        <%= store.address %>
      </div>
    </div>
  </div>
  <% end %>
</div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%# navbar logo right here %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "shopping-cart.png" %>
    <h1>SHOP SAVVY</h1>
    <% end %>


    <div class="pages">
      <%# if user_signed_in? %>
      <%= link_to "Dashboard", dashboard_path(@dashboard), class: "nav-link" %>
      <%# end %>
      <div class="nav_pages"><%= link_to "Products", search_path(@search), class: "nav-link" %></div>
      <div class="nav_pages"><%= link_to "Stores", store_path(@store), class: "nav-link" %></div>
    </div>

    <%# navbar usual code below
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>


<%# edit buttons and links along the top %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <div class="nav-item dropdown">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <%# if user_signed_in? %>
          <%= image_tag "anna@gmail.com.png", style: "width: 50px; height: 50px; border-radius: 100px", alt: "dropdown menu" %>
          <%# end %>
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Grocery", "#", class: "dropdown-item" %>
          <%= link_to "Dashboard", dashboard_path(@dashboard), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </div>
      </div>
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
        <%= link_to cart_path, class: "basket" do %>
        <%= image_tag "basket.png" %>
        <% end %>
      </ul>
      <%# else %>
      <%# <li class="nav-item"> %>
        <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
      <%# </li> %>
      <%# end %>
      </ul>
    </div>
  </div>
</div>